### ISSUE TITLE
ERROR: socketId.emit is not a function..

### ISSUE THREAD

**Issue by Yejay** [The-Older-Ones/backend-project#15]
Während der Implementierung der Lobby mit socket.io hab ich auf einmal diesen Fehler bekommen und das Backend ist abgestürzt.

![Image](https://user-images.githubusercontent.com/28364336/242965022-9b0d9d0e-5569-4693-b11f-783231e13b15.png)

![Image](https://user-images.githubusercontent.com/28364336/242965738-b9fbfd16-9307-4217-8def-4a5849668833.png)

Dinge, die ich kurz davor gemacht habe.

- Backend gepulled, für den neusten Stand. (02.06.23 um ca. 20:35 Uhr)
- console.logs im Frontend hinzugefügt und erweitert.
- Von der Landing Page (alles ausgefüllt) über die Routen zur Lobby Page navigiert und dann über den Browser den zurück Button gedrückt, um auf die Landing Page zu kommen.

Genau bei dem letzten Schritt ist der Fehler geflogen und das Backend abgestürzt. Ist auch reproduzierbar.
Kann an meinem Routing liegen, bin mir selber nicht sicher.

**Comment by Deltainu** [comment]
Bug in branch backend-project-#12 gefixed.
Sorry für die Unannehmlichkeit.
